services:
  node-exporter:
    build:
      context: node-exporter
      args:
        - FORMAT=${FORMAT:-amd64}
    container_name: node-exporter
    networks:
      - docker-practice
    restart: always
    ports:
      - ${NODE_EXPORTER_PORT:-9100}:9100

  prometheus:
    depends_on:
      - node-exporter
    build:
      context: prometheus
      args:
        - FORMAT=${FORMAT:-amd64}
    container_name: prometheus
    networks:
      - docker-practice
    restart: always
    volumes:
      -  ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - ${PROMETHEUS_PORT:-9090}:9090

  grafana:
    depends_on:
      - prometheus
    build: grafana
    container_name: grafana
    networks:
      - docker-practice
    restart: always
    environment:
      - GF_PATHS_CONFIG=/etc/grafana/grafana.ini
      - GF_PATHS_DATA=/var/lib/grafana
      - GF_PATHS_HOME=/usr/share/grafana
      # - GF_PATHS_LOGS=/var/log/grafana
      # - GF_PATHS_PLUGINS=/var/lib/grafana/plugins
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    volumes:
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
      - ./grafana/provisioning/dashboards/:/etc/grafana/provisioning/dashboards/
      - ./grafana/provisioning/datasources/:/etc/grafana/provisioning/datasources/
      - grafana-data:/var/lib/grafana
    ports:
      - ${GRAFANA_PORT:-3000}:3000

volumes:
  grafana-data:

networks:
  docker-practice:


