services:
  node-exporter:
    build: node-exporter
    container_name: node-exporter
    restart: always
    ports:
      - ${NODE_EXPORTER_PORT}:9100

  prometheus:
    depends_on:
      - node-exporter
    build: prometheus
    container_name: prometheus
    environment:
      - FORMAT=FORMAT
    restart: always
    volumes:
      -  ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - ${PROMETHEUS_PORT}:9090

  grafana:
    depends_on:
      - prometheus
    build: grafana
    container_name: grafana
    environment:
      - FORMAT=FORMAT
    restart: always
    ports:
      - ${GRAFANA_PORT}:3000

networks:
  docker-practice:


