services:
  node-exporter:
    build:
      context: node-exporter
      args:
        FORMAT: ${FORMAT:-arm64}
    container_name: node-exporter
    networks:
      - docker-practice
    restart: always
    ports:
      - ${NODE_EXPORTER_PORT:-9100}:9100

  prometheus:
    depends_on:
      - node-exporter
    build:
      context: prometheus
      args:
        FORMAT: ${FORMAT:-arm64}
    container_name: prometheus
    networks:
      - docker-practice
    restart: always
    volumes:
      -  ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - ${PROMETHEUS_PORT:-9090}:9090

  grafana:
    depends_on:
      - prometheus
    build: grafana
    container_name: grafana
    networks:
      - docker-practice
    restart: always
    ports:
      - ${GRAFANA_PORT:-3000}:3000

networks:
  docker-practice:


